### ISSUE TITLE
Zero Vaules for temp sensor in NINA

### ISSUE THREAD

**Issue by TimSha2509** [MichelMoriniaux/BigPowerBox#12]
I’ve built your powerbox and so far it worked flawlessly (thanks a lot for your amazing work!). However I just now decided to add a temperature probe and so far, Temp and Humidity will only be displayed as „0“ in NINA.

I have verified that the SHT31 sensor I’m using is actually working with the board by checking the device info in the Arduino IDE, where everything works great and the temperature is shown correctly.

I’ve already reinstalled the Ascom driver and also tried an older version to no avail so far. Any ideas what might cause this?

**Comment by MichelMoriniaux** [comment]
Hello,
is the '0' value in the switches section? it should appear there not under weather.
I would need to go to my remote observatory ( next scheduled is in 2 weeks ) to do a test and confirm ( I do not have temp probes currently plugged in)

**Comment by TimSha2509** [comment]
Hey! 

Yes it’s listed as "Env Temp" etc. right where it also appears in your screenshot on the main page. Thanks a lot for your efforts!

**Comment by rohan5sep** [comment]
While building this box I noted following: It takes over a minute for the values to be populated. Also, the temperature prob must be attached before booting up the power box.

Just sharing in case it helps...

**Comment by TimSha2509** [comment]
Omg lol. I used a faulty sensor in my first attempt and after exchanging it during trouble shooting I never bothered to wait for a whole minute. That has done the trick.

I’ll try a setup incl. the multiplexer sometime in the future and come back, should I encounter issues there, but for now this issue has been resolved thanks to your assistance!
