### ISSUE TITLE
XT60 input pcb

### ISSUE THREAD

**Issue by beshanoe** [MichelMoriniaux/BigPowerBox#2]
Hi! First of all, thanks for the amazing project! I'm thinking of building my own copy and have realized that I can't find that XT60 input group from the CN image
![image](https://github.com/MichelMoriniaux/BigPowerBox/assets/1383547/0b60692d-f2a9-4ce6-b8b2-d323538b07a9)

Is it custom made or can be bought as an assembly?

**Comment by MichelMoriniaux** [comment]
Hi!
The small board your arrow is pointing to is a 12v to 5v USB-A buck
converter, 5$ on Amazon. It's an output to power a USB device like a Raspi
for eg.

The XT60 input is the big yellow thing on the mainboard

Michel
