### ISSUE TITLE
Indi/Indigo support

### ISSUE THREAD

**Issue by rohan5sep** [MichelMoriniaux/BigPowerBox#4]
![image](https://github.com/MichelMoriniaux/BigPowerBox/assets/136604798/7fa57c5e-e16c-4ec9-9665-fb8a22d1429e)
Hi, thanks for sharing your work! I really like the project. I have ordered the PCB and planning to do the assembly myself. The only problem I am facing is that I don’t use ASCOM platform. Is there a plan to support indi? If not, can I contribute? I think can write indi/indigo driver — I will use your code as a reference. Also, could you please let me know the part number in the red rectangle? What does it do?

**Comment by MichelMoriniaux** [comment]
Unfortunately I stopped using my Indi raspberry pi so never came around to build the driver. You are more than welcome to contribute!

**Comment by MichelMoriniaux** [comment]
The part in the red rectangle is a 12v to 5v 5A buck converter, 2$ on Amazon. Not necessary but allows to have a 5v output if you need it

**Comment by rohan5sep** [comment]
So both the green arrow and red rectangle are buck converters?

**Comment by rohan5sep** [comment]
Oh got it the arrow one is usb and the red rectangle is 12v to 5v. Thanks
