### ISSUE TITLE
PWM ports do not function as expected 

### ISSUE THREAD

**Issue by rohan5sep** [MichelMoriniaux/BigPowerBox#5]
The problem is because of following code in BigPowerBox.ino file --

The routines 1. setPWMPortLevel and 2. setDewPortLevel are incorrectly accessing "ports2Pin" array. The index "port" is zero based and so is ports2Pin[] array. But it is being incorrectly accessed like so: ports2Pin[port - 1]. Because of this, wrong pins are selected. Consequently, some pins work and others are not activated ever.

Changing   ports2Pin[port - 1] to  ports2Pin[port] fixed my problems.

**Comment by MichelMoriniaux** [comment]
Thanks for the bug, that must've been a relic I forgot when I refactored the indices. I do not use that feature so missed it in testing

**Comment by MichelMoriniaux** [comment]
Closed by mistake will do a PR and then close

**Comment by rohan5sep** [comment]
Hi, i should be done with indigo driver code in few weeks. I am not sure where to submit the code. Can open a pull request here?

**Comment by MichelMoriniaux** [comment]
Yes please do a PR

**Comment by MichelMoriniaux** [comment]
fixed, PR published
