### ISSUE TITLE
PWM ports will not turn ON when configured in dew heater mode.

### ISSUE THREAD

**Issue by rohan5sep** [MichelMoriniaux/BigPowerBox#6]
This is because according to Clausius-Clapeyron equation condensation will occur when the relative humidity becomes 100%. At this point the air temperature will become equal to the dew point. The air temperature will never drop below the dew point. Therefore the code --

if(powerBoxStatus.temp < powerBoxStatus.dewpoint){...} is unlikely to be executed.

Better approach is to check/calculate the relative humidity instead. The ports can be turned ON if the relative humidity crosses a threshold say beyond 90%.

**Comment by MichelMoriniaux** [comment]
good suggestion, effectively inverting the comparison might work. IIRC I went with dewpoint as some libraries do not expose RH but only dewpoint. But again I may be mistaken.
I live in a place where humidity is non-existent so I do not use the feature, I developed it for a user that requested it. if you can debug it and get it to work I will gladly accept a pull request.

**Comment by rohan5sep** [comment]
Sure. I will create a pull request once I get it to work.

**Comment by MichelMoriniaux** [comment]
created a PR with a minimal change that might work, may cause PID issues though, please take a look

**Comment by rohan5sep** [comment]
> created a PR with a minimal change that might work, may cause PID issues though, please take a look

Will do.

**Comment by rohan5sep** [comment]
Hi, I have opened a pull request that has indigo driver code and the firmware fix for the dew heater and temperature control. I tested the dew heater and it works fine. Will test PID when I have the parts. Did you get a chance to look at the files?

**Comment by rohan5sep** [comment]
Closing as dew heater mode tested as fixed.
